# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Blendrix.com
email:
description: >- # this means to ignore newlines until "baseurl:"
  This is the official website for Blendrix, an electronic music producer and DJ from the United States. Blendrix's tracks are unique hybrids - fusing the multi-layered, hyped-up percussion and "feel-it-in-your-chest" bass of modern EDM with the intricate textures and spacious soundscapes that characterized the psychedelic rock & funk of the '60s & '70s. By blurring the line between past and present, Blendrix gives his listeners a glimpse into the future.

baseurl: "/blendrix.com" # the subpath of your site, e.g. /blog
url: "https://blendrix.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: blendrix

social:
  - title: "SoundCloud"
    url: "https://soundcloud.com/blendrix"
  - title: "YouTube"
    url: "https://www.youtube.com/user/blendrix"
  - title: "HearThis.at"
    url: "https://hearthis.at/blendrix"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
